config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'
  post 'order_complete' => 'cart#order_complete
  '

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  resources :orders
  resources :line_items
  devise_for :users

  resources :categories
  resources :products
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  
  root "storefront#all_items"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <%= link_to "My Store", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Find By Category<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |cat| %>
              <li><%= link_to cat.name, categorical_path(cat_id: cat.id) %></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Find By Brand<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% @brands.each do |brand| %>
              <li><%= link_to brand, branding_path(brand: brand) %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "My Cart", view_order_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
	      <% else %>
	        <li><%= link_to "Sign In",  new_user_session_path %></li>
        	<li><%= link_to "Forgot Password",  new_user_password_path %></li>
	      <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
<%= yield %>
</div>
</body>
</html>